name: Register and Deploy Model

on:
  push:
    branches:
      - main

jobs:
  register-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Check Azure CLI Version
        run: |
          az version

      - name: Install Azure CLI ML extension
        run: |
          az extension add -n ml -y
          az extension list

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register Model
        run: |
          az ml model register --name diabetes_model --path "outputs/model" --resource-group my-ml-resource-group --workspace-name my-ml-workspace

  deploy-model:
    runs-on: ubuntu-latest
    needs: register-model
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Check Azure CLI Version
        run: |
          az version

      - name: Install Azure CLI ML extension
        run: |
          az extension add -n ml -y
          az extension list

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Model
        run: |
          az ml online-endpoint create --name diabetes-endpoint --file endpoint.yml --resource-group my-ml-resource-group --workspace-name my-ml-workspace
          az ml online-deployment create --name blue --endpoint diabetes-endpoint --model diabetes_model:1 --file deployment.yml --resource-group my-ml-resource-group --workspace-name my-ml-workspace

  test-endpoint:
    runs-on: ubuntu-latest
    needs: deploy-model
    steps:
      - name: Test Endpoint
        run: |
          RESPONSE=$(curl -X POST https://<your-endpoint-url>/score \
          -H 'Content-Type: application/json' \
          -d '{
                "data": [
                  {
                    "Pregnancies": 9,
                    "PlasmaGlucose": 104,
                    "DiastolicBloodPressure": 51,
                    "TricepsThickness": 7,
                    "SerumInsulin": 24,
                    "BMI": 27.36983156,
                    "DiabetesPedigree": 1.350472047,
                    "Age": 43
                  }
                ]
              }')
          echo "Response: $RESPONSE"
