name: Train Model

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Train Model in Development
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run experiment job
        run: |
          az ml job create --file src/job.yml --resource-group my-ml-resource-group --workspace-name my-ml-workspace --experiment-name diabetes-dev

  production:
    name: Train Model in Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.create_url.outputs.url }}
    needs: experiment
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run production job
        run: |
          az ml job create --file src/job.yml --resource-group my-ml-resource-group --workspace-name my-ml-workspace --experiment-name diabetes-prod
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
